// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdoh7vHV_qeeTz-J2quBFygUovBIPLM4',
    appId: '1:615617259720:web:27a5e7244b4c19ae5d5dfd',
    messagingSenderId: '615617259720',
    projectId: 'injazathr-defdb',
    authDomain: 'injazathr-defdb.firebaseapp.com',
    storageBucket: 'injazathr-defdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdoh7vHV_qeeTz-J2quBFygUovBIPLM4',
    appId: '1:615617259720:android:27a5e7244b4c19ae5d5dfd',
    messagingSenderId: '615617259720',
    projectId: 'injazathr-defdb',
    storageBucket: 'injazathr-defdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdoh7vHV_qeeTz-J2quBFygUovBIPLM4',
    appId: '1:615617259720:ios:27a5e7244b4c19ae5d5dfd',
    messagingSenderId: '615617259720',
    projectId: 'injazathr-defdb',
    storageBucket: 'injazathr-defdb.firebasestorage.app',
    iosBundleId: 'com.injazatsoftware.injazathr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdoh7vHV_qeeTz-J2quBFygUovBIPLM4',
    appId: '1:615617259720:ios:27a5e7244b4c19ae5d5dfd',
    messagingSenderId: '615617259720',
    projectId: 'injazathr-defdb',
    storageBucket: 'injazathr-defdb.firebasestorage.app',
    iosBundleId: 'com.injazatsoftware.injazathr',
  );
}